version: "3.8"

networks:
  captain:
    external: true
    name: captain-overlay-network
  prom:
    external: true
    name: devops_prom
  router:
    driver: overlay
    attachable: true

configs:
  traefik_static:
    name: traefik_static-${VERSION}
    file: ./traefik.toml
  traefik_dynamic:
    name: traefik_dynamic-${VERSION}
    file: ./configs/config.yaml

secrets:
  cf_dns_api_token:
    name: cf_dns_api_token-${VERSION}
    file: ./secrets/cf_dns_api_token

volumes:
  router_certs:

services:
  traefik:
    image: "traefik:v2.5"
    networks:
      - router
      - captain
      - prom
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    configs:
      - source: traefik_static
        target: /etc/traefik/traefik.toml
      - source: traefik_dynamic
        target: /etc/traefik/configs/config.yaml
    secrets:
      - cf_dns_api_token
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
    volumes:
      - "router_certs:/etc/traefik/acme"
    deploy:
      labels:
        prometheus-job: "router"
        prometheus-port: "80"
      placement:
        constraints: [node.labels.type == router]
